Actualiza configuracion VSCode
Komorebi-AI/python-template pull request #39
Opened 2024-03-15 13:39 UTC by albertotb

Ejemplo de https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff

2024-03-15 15:56 UTC, albertotb commented
@davidggphy quizá te interesa esto

2024-03-15 20:34 UTC, davidggphy requested changes
metería el de "git.autofetch": true, para que no quede duda a nadie

2024-03-15 20:34 UTC, davidggphy commented on .vscode/settings.json
> +            "source.organizeImports": "explicit"
esto es para que las moddicaciones que no son formatting (eliminar imports, cambios como `for i in dic.keys()` -> `for i in dic`)no se haga de forma automática, o sólo para que ciertos cambios no se hagan de forma automática?

2024-03-15 23:26 UTC, albertotb commented
Explicit es que se haga de forma automática. No tengo claro si el autofetch
es algo que quieres siempre...

El vie., 15 mar. 2024 21:34, David GG ***@***.***> escribió:

> ***@***.**** requested changes on this pull request.
>
> metería el de "git.autofetch": true, para que no quede duda a nadie
> ------------------------------
>
> In .vscode/settings.json
> <https://github.com/Komorebi-AI/python-template/pull/39#discussion_r1526802687>
> :
>
> > +            "source.fixAll": "explicit",
> +            "source.organizeImports": "explicit"
>
> esto es para que las moddicaciones que no son formatting (eliminar
> imports, cambios como for i in dic.keys() -> for i in dic)no se haga de
> forma automática, o sólo para que ciertos cambios no se hagan de forma
> automática?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Komorebi-AI/python-template/pull/39#pullrequestreview-1940516515>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABRWQARHJRMYKZWV4JOL36LYYNLO5AVCNFSM6AAAAABEYAZZNGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNBQGUYTMNJRGU>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-03-18 11:10 UTC, albertotb commented
@davidggphy puedes explicar la necesidad del autofetch? Yo no lo tengo activo y no he tenido problemas, de hecho en general prefiero tenerlo desactivado

2024-03-18 11:17 UTC, davidggphy commented
> @davidggphy puedes explicar la necesidad del autofetch? Yo no lo tengo activo y no he tenido problemas, de hecho en general prefiero tenerlo desactivado

Explico el por qué traigo esto aquí. Cuando una persona se instala y empieza a configurar VSCode, le salta un pop-up donde le preguntan si quiere tener el autofetch activo o no. SI no recuerdo mal, el botón que sale más luminoso para que clickes es el de ON. Aunque por defecto, si no está en true en el config, el valor de autofetch es false.

**Creo que es mejor que toda la gente tenga lo mismo por defecto**, a menos que de verdad sepan lo que hagan. Por lo que yo optaría por dejar un valor por defecto en el config que damos.

Ahora, si es true o false ya es otra decisión. Por lo que entiendo, el autofetch lo que hace es que tu conocimiento de lo que hay en el origen esté actualizado, que normalmente se hace yendo a las ramas y haciendo pull. Desde mi desconocimiento, no veo razón por la que no es bueno que siempre tengas esto actualizado, y a veces uno se olvida de hacer pull, con lo que lo pondría a true.

2024-03-18 11:36 UTC, albertotb commented
> > @davidggphy puedes explicar la necesidad del autofetch? Yo no lo tengo activo y no he tenido problemas, de hecho en general prefiero tenerlo desactivado
> 
> Explico el por qué traigo esto aquí. Cuando una persona se instala y empieza a configurar VSCode, le salta un pop-up donde le preguntan si quiere tener el autofetch activo o no. SI no recuerdo mal, el botón que sale más luminoso para que clickes es el de ON. Aunque por defecto, si no está en true en el config, el valor de autofetch es false.
> 
> **Creo que es mejor que toda la gente tenga lo mismo por defecto**, a menos que de verdad sepan lo que hagan. Por lo que yo optaría por dejar un valor por defecto en el config que damos.
> 
> Ahora, si es true o false ya es otra decisión. Por lo que entiendo, el autofetch lo que hace es que tu conocimiento de lo que hay en el origen esté actualizado, que normalmente se hace yendo a las ramas y haciendo pull. Desde mi desconocimiento, no veo razón por la que no es bueno que siempre tengas esto actualizado, y a veces uno se olvida de hacer pull, con lo que lo pondría a true.

No es lo mismo fetch que pull. Con fetch, los cambios se descargan pero tu no ves nada en la carpeta, por lo que probablemente ni te des cuenta que está activo. Como mucho VSCode te notificará (aunque no se como ni si lo hace) que hay cambios en el remoto. Es decir, no soluciona el problema de olvidarse de hacer pull, ya que tienes que hacerlo igual (esto no es autopull).

El motivo para tenerlo desactivado es principalmente evitar que VSCode esté comunicandose constantemente con Github a ver si hay cambios, que no se con que frecuencia se hace, pero ralentiza el editor. En cualquier caso, aunque recomendemos  activarlo o desactivarlo este no es el sitio, ya que es un template te Python, no una configuración exhaustiva de VSCode. Aquí solo he puesto cosas que tienen que ver con Python y obligatorias. Este fichero normalmente no está en el control de versiones, pero al crear un repo de proyecto a partir de esta plantilla lo estará por defecto hasta que no se elimine explicitamente y se añada al gitignore. Añadir configuración opcional hace que eso sobreescriba los settings globales de los VSCode de la gente en todos los proyectos, si nos olvidamos de eliminar esto (es habitual que se mantenga en git este fichero).

2024-03-18 11:57 UTC, davidggphy commented
> * https://wiki.komorebi.ai/bin/view/Tools/Configuraci%C3%B3n%20VSCode/

Pensaba que este de aquí era el mismo que se añade en la Wiki, yo me estaba refiriendo a añadirlo en la Wiki, para que no salte la duda en la configuración en las nuevas incorporaciones (es un paso menos a explicar) https://wiki.komorebi.ai/bin/view/Tools/Configuraci%C3%B3n%20VSCode/

CUando se hace el autofetch, supongo que si entras en main te das cuenta de que estás por detrás de la rama en origin por que aparecen las flechas hacia abajo en la parte inferior de VSCode. No sé si en algún punto de la guía esta problemática está explicada.

2024-03-18 11:59 UTC, merged

2024-03-18 12:00 UTC, albertotb commented
Añadido en la wiki para quien quiera activarlo. Yo nunca he visto esas flechas en VSCode, esto está explicado en el curso en video de git, no en la guia como tal